from __future__ import annotations


class _MemoryInfo:
    total: int
    used: int


def nvmlInit() -> None: ...
def nvmlShutdown() -> None: ...
def nvmlDeviceGetHandleByIndex(index: int) -> object: ...
def nvmlDeviceGetName(handle: object) -> bytes | str: ...
def nvmlDeviceGetMemoryInfo(handle: object) -> _MemoryInfo: ...
